### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by BachToTheFuture**

### CODE REVIEW

**Comment by scottmc** [comment]
Added some possible reviewers as I'm not sure on some of the changes made.

**Review by KapiX — CHANGES_REQUESTED** [review]
You should remove the default parameters the other way around - leave them in headers and remove from source files.

**Comment by BachToTheFuture** [comment]
@KapiX changed the source code to have default parameters in header files :)

**Comment by scottmc** [comment]
Is this ready for merge now?

**Pull request merged**
